name: Development workflow

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Caching Node Modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            **/.cache
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: üß∞ Install dependencies
        run: yarn install --frozen-lockfile

      - name: üì¶ Build app
        run: yarn build

      # - name: üßπ Run lint
      #   run: yarn lint

      # - name: üêõ Run tests
      #   run: yarn test:coverage

      # - name: üî• Upload test coverage report
      #   uses: codecov/codecov-action@v1
      #   with:
      #     files: ./coverage/lcov.info
      #     token: ${{ secrets.CODECOV_TOKEN }} # only necessary for private repo

      - name: üí¨ Send Message to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              username: 'development-workflow',
              icon_emoji: ':octocat:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB}`
              }]
            }
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
